//
// Created by DemonLee on 6/3/22.
//

#ifndef TCP_IP_NETWORK_PROGRAMMING_GENERAL_H
#define TCP_IP_NETWORK_PROGRAMMING_GENERAL_H

#define BUF_SIZE 1024

#define UNKNOWN_ERR_NO 999

#endif //TCP_IP_NETWORK_PROGRAMMING_GENERAL_H
